//! ROADMAP SC-2 and SC-4, proven by ONE harness rather than two (plan 10-02).
//!
//! A ~100-event burst (D-01's locked scale) generated by FOUR concurrent real
//! `seam-client` subprocesses, landing in one receive loop and one timeline.
//! That combination proves the 200ms hook budget AND the arrival-ordering
//! guarantee in one place, and builds the expensive subprocess infrastructure
//! once.
//!
//! **Why this infrastructure is genuinely new.** Two existing things look like
//! they already do it and do not:
//!
//! - `tests/event_stream.rs::concurrent_senders_each_deliver_every_message_whole`
//!   (06-03) drives raw `UnixDatagram::unbound()` senders from THREADS inside
//!   one process. No real client binary is involved anywhere in it.
//! - `common::run_client` (07-04, via 10-01) is the only real-binary helper,
//!   and it blocks on `wait_with_output()` before returning. A loop over it is
//!   SEQUENTIAL by construction, and would pass against a server with no
//!   concurrency handling whatsoever.
//!
//! **What makes "concurrent" a fact here rather than a timing heuristic.**
//! `seam-client`'s `main` reads stdin to EOF (`read_to_string`) before it does
//! any work at all, so a child spawned with a PIPED BUT UNWRITTEN stdin is
//! blocked and alive. [`spawn_concurrent_clients`] returns every `Child` handle
//! having written nothing and waited on nothing; [`assert_all_alive`] then calls
//! `try_wait()` on each and requires `None` from all of them, which is a proof
//! that all four processes exist at the same instant. Only then does
//! [`write_all_stdins`] release them, all within microseconds of each other.
//!
//! **Delivery is MEASURED, never assumed.** `net.local.dgram.recvspace` is 4096
//! on this machine (measured three times across 06-01/06-02/06-03), so an
//! unpaced burst genuinely drops datagrams in the kernel -- 06-03 measured
//! 59.2%/60.2%/64.0% delivered across three runs of an unpaced 4x100 burst.
//! Every test below asserts the properties that survive load (no corruption, no
//! duplication, per-client order preserved, a floor on the total) and PRINTS the
//! real ratio. A test demanding 100/100 here is a test that flakes, and lowering
//! a flaky assertion later is how a phase quietly stops proving anything.
//!
//! Additive by construction: `tests/event_stream.rs` is Phase 6's regression net
//! and is not touched, and no production source changes in this plan.

// NOTE: this file deliberately carries no `#![allow(dead_code)]`. Task 1
// committed one, because the concurrency harness landed a commit before Tasks 2
// and 3 became its first callers and `clippy --all-targets -- -D warnings` is a
// phase gate. Task 3 removed it, so every item below is genuinely reached and
// the dead-code lint is live again -- unlike `common/mod.rs`, which legitimately
// needs the blanket allow because each test binary uses only part of it.

mod common;

use std::collections::{BTreeMap, BTreeSet};
use std::io::{Read, Write};
use std::os::unix::ffi::OsStrExt;
use std::path::Path;
use std::process::{Child, Command, ExitStatus, Stdio};
use std::sync::Mutex;
use std::time::{Duration, Instant};

use egui_kittest::Harness;
use seam_core::GraphEvent;
use seam_explorer_egui::app::SeamExplorerApp;
use seam_explorer_egui::event_stream;

use common::{
    client_binary, loaded_app, run_client, temp_config_home, wait_until, write_payload,
    HOOK_FILE_PATH, HOOK_REPO_RELATIVE, SOURCE_PATHS_FIXTURE,
};

// ---------------------------------------------------------------------
// Locked scale and budgets
// ---------------------------------------------------------------------

/// Four, mirroring 06-03's proven four-sender shape -- but four real OS
/// processes rather than four threads.
const CLIENTS: usize = 4;

/// 25 each, so the burst totals D-01's ~100 events.
const SYMBOLS_PER_CLIENT: usize = 25;

/// D-01's locked burst scale. Declared separately and cross-checked against
/// the two constants above, so a later edit to either cannot silently change
/// what this file claims to measure.
const BURST_TOTAL: usize = 100;

/// Serializes every test in this file. Tasks 2 and 3 drive the process-global
/// receiver (`event_stream::serve` plus the `received_count`/`discarded_count`/
/// `dropped_count` it backs), so one lock for the whole file, following
/// `timeline_reconstruction.rs`'s and `crash_relaunch.rs`'s one-lock-per-file
/// discipline.
///
/// This is a plain PROCESS-LOCAL mutex, not a file lock: it serializes tests
/// inside THIS binary and nothing else. Cross-process safety comes entirely
/// from `common::temp_config_home` embedding `std::process::id()`.
static SERVE_TEST_LOCK: Mutex<()> = Mutex::new(());

/// Generous: this waits on real process spawns plus real socket hops, and only
/// ever runs to completion when something has genuinely gone wrong.
const ARRIVAL_DEADLINE: Duration = Duration::from_secs(10);

/// D-01's locked hook budget, the same 200ms `fail_open.rs` and
/// `crash_relaunch.rs` enforce. SC-2's "does not slow the user's Claude Code
/// session" half is exactly this number.
///
/// Locked BEFORE the measurement precisely so it could not be negotiated after
/// seeing the result. If a warm binary ever exceeds it, report the measurement
/// and record a WINDOWS entry -- do not relax the constant.
const HOOK_BUDGET: Duration = Duration::from_millis(200);

/// The frame-stall ceiling for SC-2's visualizer half.
///
/// Deliberately far ABOVE 06-03's measured 828us maximum under flood and far
/// BELOW anything a user would experience as a freeze. It exists to fail on a
/// real cliff, not to certify a performance target -- so a passing run says
/// "nothing caught fire", and the printed max/median/mean are what actually
/// describe the cadence.
const FRAME_STALL_CEILING: Duration = Duration::from_millis(250);

// ---------------------------------------------------------------------
// The payload
// ---------------------------------------------------------------------

/// The tag that carries a client's identity into every id it advertises.
fn client_tag(index: usize) -> String {
    format!("c{index}")
}

/// One symbol name, zero-padded so lexicographic order and numeric order
/// coincide -- which is what lets [`reference_order`] state the expected
/// emission order without restating `detect`'s `BTreeSet` semantics.
fn symbol(client: usize, n: usize) -> String {
    format!("{}_sym_{n:02}", client_tag(client))
}

/// The node id `seam-client` will advertise for `symbol(client, n)`, built from
/// DP-07-01's `{source_file}::{symbol}` identity and
/// [`common::HOOK_REPO_RELATIVE`] -- never by reading an id back out of the app
/// and re-parsing it. An expectation read out of the system under test cannot
/// fail (`timeline_reconstruction.rs`'s discipline).
fn expected_node_id(client: usize, n: usize) -> String {
    format!("{HOOK_REPO_RELATIVE}::{}", symbol(client, n))
}

/// The order one client's advertisements are emitted in, which Task 1 PROVES
/// against a real single-client run rather than asserting from the source of
/// `detect`.
fn reference_order(client: usize) -> Vec<String> {
    let mut ids: Vec<String> = (0..SYMBOLS_PER_CLIENT)
        .map(|n| expected_node_id(client, n))
        .collect();
    // Sorted explicitly rather than relying on the zero-padding to make the
    // generated order already lexicographic: the claim being expressed is
    // "lexicographic", so the code should say it.
    ids.sort();
    ids
}

/// A `Write`-shaped hook payload declaring `SYMBOLS_PER_CLIENT` top-level
/// `pub fn`s named `symbol(client, 0..SYMBOLS_PER_CLIENT)`.
///
/// Three constraints on the generated content, each load-bearing:
///
/// - **No `::` anywhere, and no top-level `use` line.** Both of `detect`'s
///   reference rules key on those (`collect_import` wants a column-zero
///   `use `; `collect_qualified_calls` walks back from every `(` and keeps the
///   run only if it contains `::`). Any reference would add `AddEdge` events,
///   making the emitted count per client something other than
///   `SYMBOLS_PER_CLIENT` and turning every count assertion in this file into
///   guesswork. The bodies are therefore `{ 0 }` with no calls. Task 1 CHECKS
///   this behaviourally rather than trusting it.
/// - **The client index is in the symbol name**, so the resulting node id
///   (`src/auth/login.rs::c2_sym_07`) carries its own origin. Attribution in
///   the merged timeline is then a property of the data and needs no side
///   channel.
/// - **The edited file is a real `source_file` of the fixture**
///   ([`common::HOOK_FILE_PATH`] is the `source_file` of fixture node `a1`), so
///   sibling inheritance resolves every advertised node to a concrete
///   community and every event is genuinely APPLIED and therefore RECORDED. An
///   unknown file would leave the events parked in the unknown bucket or minted
///   into a `__live__:` community, and an ordering assertion over events that
///   never reached the history would be measuring nothing.
///
/// `tool_response.originalFile` is `null` in `common::write_payload`'s captured
/// shape, so this reads as a CREATE: the before-text is empty and all
/// `SYMBOLS_PER_CLIENT` definitions are additions.
fn burst_payload(client: usize) -> String {
    let mut content = String::new();
    for n in 0..SYMBOLS_PER_CLIENT {
        // `-> usize { 0 }` rather than a bare `{}` so the lines look like real
        // code, while still containing no parenthesised call and no path
        // separator for `collect_qualified_calls` to find.
        content.push_str(&format!(
            "pub fn {}() -> usize {{ 0 }}\n",
            symbol(client, n)
        ));
    }
    write_payload(HOOK_FILE_PATH, &content)
}

// ---------------------------------------------------------------------
// The concurrency harness -- split where `common::run_client` is not
// ---------------------------------------------------------------------

/// Spawns `count` real `seam-client` processes with piped stdin and writes
/// NOTHING to any of them, returning every handle.
///
/// **This function waits on nothing, and that is the whole point.** It is the
/// mitigation for T-10-02-02 and for research's Pitfall 3: `common::run_client`
/// blocks on `wait_with_output()` before returning, so a loop over it LOOKS
/// like a multi-client test while being sequential by construction -- and would
/// pass against a server with no concurrency handling at all. Splitting spawn
/// from wait is what makes four-at-once achievable; [`assert_all_alive`] is
/// what makes it a checked fact.
///
/// Each child gets `XDG_CONFIG_HOME` set and `CLAUDE_PROJECT_DIR` removed, so
/// it independently resolves the same socket path through
/// `seam_core::default_socket_path` -- exactly as `common::run_client` does.
fn spawn_concurrent_clients(config_home: &Path, count: usize) -> Vec<Child> {
    let binary = client_binary();
    (0..count)
        .map(|index| {
            Command::new(&binary)
                .env("XDG_CONFIG_HOME", config_home)
                .env_remove("CLAUDE_PROJECT_DIR")
                .stdin(Stdio::piped())
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()
                .unwrap_or_else(|e| {
                    panic!(
                        "spawn concurrent client {index} at {}: {e}",
                        binary.display()
                    )
                })
        })
        .collect()
}

/// Requires every child to still be running, at one instant.
///
/// This is the deterministic core of this file's concurrency claim. `main` in
/// `seam-client` calls `read_to_string` on stdin before it does anything else,
/// so a child whose stdin is piped and UNWRITTEN is parked in its own `read`.
/// `try_wait()` returning `None` for all of them therefore means all `count`
/// processes genuinely exist simultaneously -- no sleep, no "spawned close
/// together and hope", nothing timing-dependent.
fn assert_all_alive(children: &mut [Child]) {
    let total = children.len();
    for (index, child) in children.iter_mut().enumerate() {
        let status = child
            .try_wait()
            .unwrap_or_else(|e| panic!("try_wait on concurrent client {index}: {e}"));
        assert!(
            status.is_none(),
            "concurrent client {index} had already exited with {status:?} before any stdin was \
             written -- every one of the {total} children must be blocked in its own stdin read at \
             this instant, which is what makes 'all {total} ran at once' a fact rather than a \
             timing heuristic"
        );
    }
}

/// Releases every child within microseconds of the others by writing its
/// payload and CLOSING its stdin (the `drop` is what produces the EOF
/// `read_to_string` is waiting for).
fn write_all_stdins(children: &mut [Child], payloads: &[String]) {
    assert_eq!(
        children.len(),
        payloads.len(),
        "one payload per child, or a client would be released with nothing to do"
    );
    for (index, (child, payload)) in children.iter_mut().zip(payloads).enumerate() {
        let mut stdin = child
            .stdin
            .take()
            .unwrap_or_else(|| panic!("child {index}'s stdin was piped"));
        // The write result is deliberately ignored, matching `common::run_client`
        // and `fail_open.rs`: a client that declines an over-ceiling payload
        // closes the pipe, and the writer seeing that is correct behaviour
        // rather than a test failure.
        let _ = stdin.write_all(payload.as_bytes());
        drop(stdin);
    }
}

/// Waits on every child AFTER all of them have been released, asserting the
/// hook contract on each: exit 0, empty stdout, empty stderr.
fn wait_all_clients(children: Vec<Child>) {
    let mut children = children;
    for (index, child) in children.iter_mut().enumerate() {
        let status = child
            .wait()
            .unwrap_or_else(|e| panic!("wait for concurrent client {index}: {e}"));
        assert_hook_contract(index, child, status);
    }
}

/// The hook contract, in one place so the blocking path ([`wait_all_clients`])
/// and the frame-stepping path ([`poll_exits`]) cannot drift about what a
/// well-behaved invocation looks like.
///
/// stdout/stderr are read from the piped handles rather than through
/// `wait_with_output`, because the cadence test must reap its children with
/// `try_wait` while it keeps stepping frames and so cannot consume them.
fn assert_hook_contract(index: usize, child: &mut Child, status: ExitStatus) {
    assert!(
        status.success(),
        "concurrent client {index} must exit 0 like any hook, got {status:?}"
    );
    let mut stdout = String::new();
    if let Some(mut handle) = child.stdout.take() {
        let _ = handle.read_to_string(&mut stdout);
    }
    let mut stderr = String::new();
    if let Some(mut handle) = child.stderr.take() {
        let _ = handle.read_to_string(&mut stderr);
    }
    assert_eq!(stdout, "", "concurrent client {index} must print nothing");
    assert_eq!(
        stderr, "",
        "concurrent client {index} must print nothing to stderr"
    );
}

/// Polls every not-yet-reaped child ONCE, recording any that have exited and
/// asserting the hook contract on it there and then. Returns `true` once every
/// child has been accounted for.
///
/// Non-blocking on purpose: the cadence test has to keep driving real frames
/// while the burst lands, so it cannot afford a blocking `wait`.
fn poll_exits(children: &mut [Child], reaped: &mut [bool]) -> bool {
    for (index, child) in children.iter_mut().enumerate() {
        if reaped[index] {
            continue;
        }
        let status = child
            .try_wait()
            .unwrap_or_else(|e| panic!("try_wait on concurrent client {index}: {e}"));
        if let Some(status) = status {
            assert_hook_contract(index, child, status);
            reaped[index] = true;
        }
    }
    reaped.iter().all(|done| *done)
}

// ---------------------------------------------------------------------
// Small shared readers
// ---------------------------------------------------------------------

fn assert_sun_path_fits(path: &Path) {
    let len = path.as_os_str().as_bytes().len();
    assert!(
        len <= seam_core::MAX_SUN_PATH_BYTES,
        "socket path is {len} bytes, over the {} byte sun_path ceiling: {}",
        seam_core::MAX_SUN_PATH_BYTES,
        path.display()
    );
}

/// The id an `AddNode` carries, or nothing for any other event kind.
fn node_id_of(event: &GraphEvent) -> Option<String> {
    match event {
        GraphEvent::AddNode { id, .. } => Some(id.clone()),
        _ => None,
    }
}

/// Drives the REAL `eframe::App::ui`, so the drain, the apply, the SCC
/// recompute, the seam re-detect and the history record all run on the real
/// per-frame path. Copied in shape from `crash_relaunch.rs` and
/// `timeline_reconstruction.rs`.
fn app_ui_harness(app: SeamExplorerApp) -> Harness<'static, SeamExplorerApp> {
    let mut frame = eframe::Frame::_new_kittest();
    Harness::new_ui_state(
        move |ui, app: &mut SeamExplorerApp| {
            <SeamExplorerApp as eframe::App>::ui(app, ui, &mut frame);
        },
        app,
    )
}

/// The node ids in the TIMELINE, in timeline order -- `app.history`, not the
/// raw channel and not `app.model`. SC-4's claim is about what landed in the
/// one timeline.
fn recorded_node_ids(app: &SeamExplorerApp) -> Vec<String> {
    app.history
        .iter()
        .filter_map(|entry| node_id_of(&entry.event))
        .collect()
}

/// How long the recorded-event count must hold still before a burst is
/// considered fully absorbed.
///
/// A settling window rather than a target count, because the target count is
/// exactly what is NOT known in advance here: an unpaced burst against a
/// 4096-byte kernel receive buffer loses an unpredictable number of datagrams,
/// so "wait for 100" would always run to its deadline.
const SETTLE_WINDOW: Duration = Duration::from_millis(500);

/// Steps real frames until `history.next_seq()` has not moved for
/// [`SETTLE_WINDOW`], timing every step. Returns the per-step durations so a
/// caller that cares about frame cadence can measure it.
fn step_until_settled(harness: &mut Harness<'static, SeamExplorerApp>) -> Vec<Duration> {
    let mut durations = Vec::new();
    let mut last = harness.state().history.next_seq();
    let mut quiet_since = Instant::now();
    let deadline = Instant::now() + ARRIVAL_DEADLINE;
    loop {
        let start = Instant::now();
        harness.run_steps(1);
        durations.push(start.elapsed());

        let now = harness.state().history.next_seq();
        if now != last {
            last = now;
            quiet_since = Instant::now();
        }
        if quiet_since.elapsed() >= SETTLE_WINDOW {
            return durations;
        }
        assert!(
            Instant::now() < deadline,
            "the recorded-event count never settled: still at {last} after {:?}",
            ARRIVAL_DEADLINE
        );
        // Outside the timed region on purpose: this paces the polling, it is
        // not part of any frame's cost.
        std::thread::sleep(Duration::from_millis(5));
    }
}

/// Runs one real client against a config home with NO socket at all, purely to
/// pay the host OS's first-exec cost before a measurement.
///
/// WINDOWS 34: the first execution of a freshly built binary costs 270-319ms
/// versus ~5ms warm, and that is host-OS per-inode overhead rather than client
/// code. A cold exec inside a burst would also stagger the release of the four
/// children by that much, making the concurrency weaker than the harness
/// guarantees.
///
/// The warm-up deliberately fires at a NON-EXISTENT socket path so it cannot
/// put an event into the timeline under test -- the client's `send_to` simply
/// fails and it exits 0 in silence, which `common::run_client` still asserts.
fn warm_the_client_binary(unique: &str) {
    let cold_home = temp_config_home(unique);
    run_client(
        &cold_home,
        &write_payload(HOOK_FILE_PATH, "pub fn warm_up() -> usize { 0 }\n"),
    );
    let _ = std::fs::remove_dir_all(&cold_home);
}

/// Every id this burst could legitimately produce, mapped to the client that
/// would have produced it.
///
/// Built from [`expected_node_id`] -- the same function that built the payload
/// -- never by reading ids back out of the app and re-parsing them into an
/// expectation.
fn legal_ids() -> BTreeMap<String, usize> {
    (0..CLIENTS)
        .flat_map(|client| {
            (0..SYMBOLS_PER_CLIENT).map(move |n| (expected_node_id(client, n), client))
        })
        .collect()
}

/// Whether `candidate` appears inside `reference` in order, possibly with gaps.
///
/// This is the falsifiable core of "correctly ordered" under D-02: losing
/// datagrams to the kernel is expected and leaves a subsequence intact, while a
/// framing bug, a re-sort, or any per-client reordering breaks it. An
/// INTERLEAVING between clients -- expected and allowed under server-arrival
/// ordering -- does not affect it, because each client is checked against its
/// own reference.
fn is_subsequence(candidate: &[String], reference: &[String]) -> bool {
    let mut remaining = reference.iter();
    candidate
        .iter()
        .all(|wanted| remaining.any(|seen| seen == wanted))
}

// ---------------------------------------------------------------------
// Task 1 -- the reference run
// ---------------------------------------------------------------------

/// ONE client, through `common::run_client`, fixing the per-client emission
/// order every later assertion is measured against.
///
/// Three things this test establishes, in order:
///
/// 1. **The payload produces NODES ONLY.** Exactly `SYMBOLS_PER_CLIENT`
///    `AddNode` events arrive and ZERO `AddEdge` events, which is
///    [`burst_payload`]'s no-`::`/no-`use` constraint CHECKED rather than
///    assumed. Any edge would make the per-client count something other than
///    `SYMBOLS_PER_CLIENT` and turn every count assertion in this file into
///    guesswork.
/// 2. **The emitted order is the lexicographic order of the symbol names**,
///    which is what `detect`'s `BTreeSet` set-difference determinism means in
///    practice. [`reference_order`] is then the authority every later
///    assertion compares against, so no test in this file assumes `detect`'s
///    internal iteration order.
/// 3. **It WARMS the client binary** for the budget measurement in
///    `a_concurrent_burst_stays_inside_the_hook_budget`. WINDOWS 34: the first
///    execution of a freshly built binary costs 270-319ms (host-OS per-inode
///    overhead, not client code) versus ~5ms warm. Cargo gives no ordering
///    guarantee between tests, so that test warms explicitly as well -- this
///    is a useful side effect, not a dependency.
///
/// A single client's 25 small datagrams through a warm receive loop should
/// arrive whole, so the count below is an EXACT assertion, not a floor. If it
/// ever fails, that is a finding about the kernel receive buffer at this
/// datagram size that Task 2's numbers depend on -- report it with the real
/// counters rather than lowering the bar.
#[test]
fn a_single_client_reference_run_fixes_the_per_client_emission_order() {
    let _guard = SERVE_TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());

    let config_home = temp_config_home("c1ref");
    let socket_path = seam_core::socket_path_from(config_home.to_str(), None)
        .expect("the socket path must resolve from an explicit base");
    assert_sun_path_fits(&socket_path);

    let socket =
        event_stream::bind_at(&socket_path).expect("bind_at must succeed for a fresh path");
    // `spawn_receiver`, not `serve`: this test wants the RAW arrival list
    // including any event kind, so it can assert that no `AddEdge` was emitted
    // at all. An edge that was parked or dropped by the apply pipeline would
    // never reach a history, so a history-level check could not see it.
    let receiver = event_stream::spawn_receiver(socket, egui::Context::default());

    run_client(&config_home, &burst_payload(0));

    let mut drained: Vec<GraphEvent> = Vec::new();
    wait_until(ARRIVAL_DEADLINE, || {
        drained.extend(receiver.drain());
        drained.len() >= SYMBOLS_PER_CLIENT
    });
    // One more poll after the wait: a datagram that arrived during the final
    // sleep would otherwise be invisible to the exactness assertions below.
    drained.extend(receiver.drain());

    let edges = drained
        .iter()
        .filter(|event| !matches!(event, GraphEvent::AddNode { .. }))
        .count();
    assert_eq!(
        edges, 0,
        "the generated content must produce NODES ONLY -- {edges} non-AddNode events arrived, so \
         `burst_payload`'s no-`::`/no-`use` constraint has been broken and every per-client count \
         in this file is now guesswork. Arrivals: {drained:?}"
    );
    assert_eq!(
        drained.len(),
        SYMBOLS_PER_CLIENT,
        "exactly {SYMBOLS_PER_CLIENT} AddNode events must arrive from one client; received={} \
         discarded={} dropped={}. Do NOT lower this -- a loss here is a finding about the kernel \
         receive buffer at this datagram size, and Task 2's numbers depend on it",
        receiver.stats().received(),
        receiver.stats().discarded(),
        receiver.stats().dropped()
    );

    let arrived: Vec<String> = drained.iter().filter_map(node_id_of).collect();
    let expected = reference_order(0);
    eprintln!(
        "[10-02 Task 1] reference emission order for client 0 ({} ids): {:?}",
        arrived.len(),
        arrived
    );
    assert_eq!(
        arrived, expected,
        "one client's emission order must be the lexicographic order of its symbol names -- that \
         is what `detect`'s BTreeSet set-difference determinism means in practice, and it is what \
         every per-client subsequence assertion in this file is measured against"
    );

    let _ = std::fs::remove_dir_all(&config_home);
}

// ---------------------------------------------------------------------
// Task 2 -- four concurrent sessions, one arrival-ordered timeline
// ---------------------------------------------------------------------

/// ROADMAP SC-4 with D-02's locked semantics: events from four SIMULTANEOUSLY
/// LIVE real `seam-client` processes land in ONE timeline ordered by server
/// arrival, and each client's own events appear in that timeline in the order
/// that client emitted them.
///
/// No new ordering mechanism is introduced or needed. Sequence ids are assigned
/// by `History::push` in the order the receive loop got the datagrams
/// (`apply_batch`'s "in the order received", over a FIFO `sync_channel`), and
/// nothing in the wire event participates in ordering at all -- which is
/// T-10-02-03's mitigation stated as an assertion rather than as a design note.
///
/// **Full delivery is deliberately NOT asserted, and that is not laziness.**
/// `net.local.dgram.recvspace` is 4096 bytes on this machine, so an unpaced
/// burst of ~100 datagrams from four separate processes genuinely loses some in
/// the kernel before the receive loop can read them -- 06-03 measured 59.2%,
/// 60.2% and 64.0% delivered across three runs of a heavier unpaced 4x100
/// burst. What IS asserted is everything that survives load: no corruption, no
/// duplication, per-client order preserved, at least one event from every
/// client, a floor on the total, and ZERO discards. The real ratio is printed.
///
/// **An honest observation about what this run actually measures.** All four
/// processes are provably alive at one instant (that is [`assert_all_alive`]'s
/// whole job, and it is a real proof). Their DATAGRAMS, however, have been
/// observed arriving in four CONTIGUOUS runs rather than interleaved -- the
/// printed `interleaving` figure says which happened on any given run. That is
/// not a defect and not a weakness of the harness: each client's send loop is
/// ~25 `send_to` syscalls over a few microseconds, short enough that the
/// scheduler routinely runs one to completion before the next is released, and
/// 25 datagrams fit inside the measured 4096-byte receive buffer. Contiguous
/// arrival is perfectly legal under D-02's server-arrival-order semantics, and
/// the per-client subsequence check below is STRICTER in that case (it degrades
/// to full equality per client), not weaker. What this test does NOT claim is
/// that interleaved arrival has been exercised; forcing it would require pacing
/// inside `seam-client`, and this plan changes no production code.
#[test]
fn four_concurrent_clients_land_in_one_arrival_ordered_timeline() {
    let _guard = SERVE_TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());

    assert_eq!(
        CLIENTS * SYMBOLS_PER_CLIENT,
        BURST_TOTAL,
        "scale guard: D-01 locked a ~100-event burst, and the two constants must still produce it"
    );

    // Warm first, so the four children are released into their real work
    // rather than into a 270-319ms cold exec (WINDOWS 34).
    warm_the_client_binary("c1wrm2");

    let config_home = temp_config_home("c1ord");
    let socket_path = seam_core::socket_path_from(config_home.to_str(), None)
        .expect("the socket path must resolve from an explicit base");
    assert_sun_path_fits(&socket_path);
    let socket =
        event_stream::bind_at(&socket_path).expect("bind_at must succeed for a fresh path");

    let app = loaded_app(SOURCE_PATHS_FIXTURE);
    let mut harness = app_ui_harness(app);
    // `serve` BEFORE the first frame, so the process-global receiver is
    // unambiguously this test's and all three counters start from zero.
    event_stream::serve(socket, harness.ctx.clone());
    harness.run_steps(3);

    assert_eq!(
        harness.state().history.next_seq(),
        0,
        "guard: nothing may have been recorded before the burst fires"
    );
    assert_eq!(
        event_stream::received_count(),
        0,
        "guard: this test's receiver must start from zero, or every ratio below is someone \
         else's measurement"
    );

    // The burst: spawn all four, prove all four are alive at one instant, then
    // release them together.
    let payloads: Vec<String> = (0..CLIENTS).map(burst_payload).collect();
    let mut children = spawn_concurrent_clients(&config_home, CLIENTS);
    assert_all_alive(&mut children);
    write_all_stdins(&mut children, &payloads);
    wait_all_clients(children);

    let _ = step_until_settled(&mut harness);

    let app = harness.state();
    let entries: Vec<(u64, GraphEvent)> = app
        .history
        .iter()
        .map(|entry| (entry.seq, entry.event.clone()))
        .collect();
    let recorded = recorded_node_ids(app);

    // ---- 1. One timeline, densely and monotonically numbered ----
    assert_eq!(
        app.history.evicted_count(),
        0,
        "scale guard: {BURST_TOTAL} events cannot exceed the {} buffer, so the dense 0..n-1 claim \
         below is about the WHOLE timeline rather than a retained window",
        app.history.capacity()
    );
    let seqs: Vec<u64> = entries.iter().map(|(seq, _)| *seq).collect();
    let expected_seqs: Vec<u64> = (0..entries.len() as u64).collect();
    assert_eq!(
        seqs, expected_seqs,
        "the recorded sequence ids must be exactly 0..n-1 in timeline order -- `History::push` \
         assigns them server-side in arrival order and nothing re-sorts them"
    );
    assert_eq!(
        app.history.next_seq(),
        entries.len() as u64,
        "next_seq must equal the number of events recorded"
    );

    // ---- 2. Attribution is total and exclusive ----
    let legal = legal_ids();
    let mut seen: BTreeSet<&String> = BTreeSet::new();
    let mut per_client: Vec<Vec<String>> = vec![Vec::new(); CLIENTS];
    let mut client_sequence: Vec<usize> = Vec::with_capacity(entries.len());
    for (seq, event) in &entries {
        let id = node_id_of(event).unwrap_or_else(|| {
            panic!("every recorded event must be an AddNode; seq {seq} holds {event:?}")
        });
        let client = *legal.get(&id).unwrap_or_else(|| {
            panic!(
                "recorded id `{id}` (seq {seq}) is not one this burst could have produced -- an \
                 unparseable id means corruption, a merge of two clients' datagrams, or a framing \
                 bug"
            )
        });
        let id_ref = legal
            .get_key_value(&id)
            .map(|(key, _)| key)
            .expect("just looked it up");
        assert!(
            seen.insert(id_ref),
            "`{id}` appears twice in the timeline (second at seq {seq}) -- a duplicate means a \
             datagram was delivered twice"
        );
        per_client[client].push(id.clone());
        client_sequence.push(client);
    }

    // ---- 3. Per-client order is preserved ----
    for (client, landed) in per_client.iter().enumerate() {
        let reference = reference_order(client);
        assert!(
            is_subsequence(landed, &reference),
            "client {client}'s events must appear in the timeline in the order that client \
             emitted them. Recorded for client {client}: {landed:?}. Reference emission order: \
             {reference:?}"
        );
    }

    // ---- 4. Every client got through ----
    let counts: Vec<usize> = per_client.iter().map(Vec::len).collect();
    for (client, landed) in per_client.iter().enumerate() {
        assert!(
            !landed.is_empty(),
            "every one of the {CLIENTS} concurrent clients must have landed at least one event in \
             the timeline, and client {client} landed none; per-client counts were {counts:?} over \
             {} recorded events",
            recorded.len()
        );
    }

    // ---- 5. A delivery floor, plus the real number ----
    // `runs` counts how many times the timeline switches from one client to
    // another. Anything above CLIENTS is direct evidence the four processes
    // were genuinely racing on the socket rather than being serialized.
    let runs = client_sequence
        .windows(2)
        .filter(|pair| pair[0] != pair[1])
        .count()
        + usize::from(!client_sequence.is_empty());
    eprintln!(
        "[10-02 Task 2] {CLIENTS} concurrent real clients x {SYMBOLS_PER_CLIENT} symbols\n  \
         delivered/sent: {}/{BURST_TOTAL} ({:.1}%)\n  \
         per-client counts: {counts:?}\n  \
         interleaving: {runs} client runs across the timeline (> {CLIENTS} means genuinely \
         interleaved)\n  \
         counters: received={} discarded={} dropped={}",
        recorded.len(),
        100.0 * recorded.len() as f64 / BURST_TOTAL as f64,
        event_stream::received_count(),
        event_stream::discarded_count(),
        event_stream::dropped_count(),
    );
    assert!(
        recorded.len() >= BURST_TOTAL / 2,
        "at least half of the {BURST_TOTAL}-event burst must reach the timeline; only {} did \
         (received={} discarded={} dropped={})",
        recorded.len(),
        event_stream::received_count(),
        event_stream::discarded_count(),
        event_stream::dropped_count()
    );
    assert_eq!(
        event_stream::discarded_count(),
        0,
        "a discard is a wire-shape REJECTION, not load: under SOCK_DGRAM it means something \
         arrived malformed, which is a corruption claim about four concurrent real clients and \
         must be investigated rather than tolerated"
    );

    // ---- 6. The graph agrees with the timeline ----
    let model = app.model.as_ref().expect("the fixture must be loaded");
    for id in &recorded {
        assert!(
            model.index.contains_key(id),
            "`{id}` is in the timeline but not in the live model -- a history entry whose event \
             never applied would satisfy 'landed in the timeline' while meaning nothing"
        );
    }

    let _ = std::fs::remove_dir_all(&config_home);
}

// ---------------------------------------------------------------------
// Task 3 -- the two budgets: the hook stays cheap, the visualizer stays alive
// ---------------------------------------------------------------------

/// SC-2's "does not slow the user's Claude Code session" half, at D-01's locked
/// scale and budget (~100 events, 200ms).
///
/// **Why a total bounds every individual invocation.** All four children are
/// spawned and confirmed alive FIRST, each parked in its own stdin read. The
/// clock then starts at the instant the stdins are written and stops when the
/// last child has been waited on. Because every child begins its work within
/// microseconds of that write, the elapsed total is an upper bound on EVERY
/// invocation's own latency: if the whole concurrent burst finishes inside
/// `HOOK_BUDGET`, no single hook invocation exceeded it.
///
/// **What that window excludes, stated rather than glossed.** Because the
/// children are already spawned when the clock starts, the measured window does
/// NOT include process spawn/exec -- it is read, parse, detect, send, exit. A
/// real hook invocation pays the spawn too, so a second figure covering
/// spawn-to-exit is measured and asserted against the same budget. 07-04's
/// `fail_open.rs::best_of_five` measures the spawn-inclusive form for one client
/// and got 3.8ms warm; this is its four-concurrent-clients counterpart.
///
/// **The binary must be warm.** WINDOWS 34: the first execution of a freshly
/// built binary costs 270-319ms against a 200ms budget, and that is host-OS
/// per-inode overhead, not client code. The budget claim is about the warm
/// binary a user actually has registered as a hook. Cargo gives no ordering
/// guarantee between tests, so this test warms explicitly rather than relying on
/// the reference run having gone first.
#[test]
fn a_concurrent_burst_stays_inside_the_hook_budget() {
    let _guard = SERVE_TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());

    warm_the_client_binary("c1wrm3");

    let config_home = temp_config_home("c1bud");
    let socket_path = seam_core::socket_path_from(config_home.to_str(), None)
        .expect("the socket path must resolve from an explicit base");
    assert_sun_path_fits(&socket_path);
    let socket =
        event_stream::bind_at(&socket_path).expect("bind_at must succeed for a fresh path");
    // A real LIVE receiver, so this measures the path a user actually has --
    // sending to a bound socket with something reading it. `fail_open.rs`
    // already covers the nothing-listening case.
    let receiver = event_stream::spawn_receiver(socket, egui::Context::default());

    let payloads: Vec<String> = (0..CLIENTS).map(burst_payload).collect();

    let spawn_start = Instant::now();
    let mut children = spawn_concurrent_clients(&config_home, CLIENTS);
    assert_all_alive(&mut children);

    let release = Instant::now();
    write_all_stdins(&mut children, &payloads);
    wait_all_clients(children);
    let released_to_exit = release.elapsed();
    let spawn_to_exit = spawn_start.elapsed();

    let mut arrived = 0usize;
    wait_until(ARRIVAL_DEADLINE, || {
        arrived += receiver.drain().len();
        arrived >= BURST_TOTAL
    });
    arrived += receiver.drain().len();

    eprintln!(
        "[10-02 Task 3] hook budget, {CLIENTS} concurrent WARM clients x {SYMBOLS_PER_CLIENT} \
         symbols = {BURST_TOTAL} events\n  \
         released -> last exit: {released_to_exit:?} against a {HOOK_BUDGET:?} budget\n  \
         spawned  -> last exit: {spawn_to_exit:?} (includes exec of {CLIENTS} processes plus this \
         harness's own try_wait pass)\n  \
         arrived at the receiver: {arrived}/{BURST_TOTAL}\n  \
         cold-start caveat: WINDOWS 34 measured 270-319ms for the FIRST exec of a freshly built \
         binary; the binary was warmed explicitly before this measurement"
    );

    assert!(
        released_to_exit < HOOK_BUDGET,
        "the whole concurrent burst took {released_to_exit:?}, over D-01's {HOOK_BUDGET:?} budget \
         -- so at least one hook invocation exceeded it. Do NOT relax the budget: report the \
         measurement and record a WINDOWS entry saying SC-2's Claude-Code-session half is unmet at \
         this scale on this host"
    );
    assert!(
        spawn_to_exit < HOOK_BUDGET,
        "spawn-to-exit for {CLIENTS} concurrent clients took {spawn_to_exit:?}, over the \
         {HOOK_BUDGET:?} budget. This is the spawn-INCLUSIVE figure, which is what a real hook \
         invocation pays"
    );

    let _ = std::fs::remove_dir_all(&config_home);
}

/// SC-2's "does not freeze, flood, or wedge the visualizer" half, and the
/// mitigation for T-10-02-01.
///
/// The real assembled `eframe::App::ui` is driven through `app_ui_harness`
/// while the burst lands: spawn, confirm all four alive, write the stdins, then
/// immediately loop stepping frames and timing each one until every child has
/// exited and the arrival count has settled.
///
/// Four claims, each one guarding against a different way this could pass while
/// meaning nothing:
///
/// 1. **The burst genuinely arrived during the timed window** -- the recorded
///    event count grew by a non-zero amount across it. Without this the whole
///    measurement is of an idle app, the exact trap
///    `the_render_loop_keeps_its_cadence_while_datagrams_stream_in` calls out.
/// 2. **No frame reached `FRAME_STALL_CEILING`**, with max/median/mean printed.
/// 3. **Loss was COUNTED, not stalled.** `try_send` never blocks, so a
///    saturated channel increments `dropped` instead of making a hook process
///    wait. Every datagram the receive loop saw is accounted for as
///    received/dropped/discarded, and everything the channel delivered reached
///    the timeline.
/// 4. **The app is not wedged** -- a post-burst liveness probe (one more real
///    client invocation) still delivers, applies and records, and its node is in
///    `app.model`. That probe is what distinguishes "absorbed the burst" from
///    "survived it in a broken state", mirroring the liveness bracketing 06-03
///    put around its hostile corpus.
#[test]
fn the_app_keeps_its_frame_cadence_through_a_concurrent_burst_and_is_still_live_after() {
    let _guard = SERVE_TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());

    warm_the_client_binary("c1wrm4");

    let config_home = temp_config_home("c1cad");
    let socket_path = seam_core::socket_path_from(config_home.to_str(), None)
        .expect("the socket path must resolve from an explicit base");
    assert_sun_path_fits(&socket_path);
    let socket =
        event_stream::bind_at(&socket_path).expect("bind_at must succeed for a fresh path");

    let app = loaded_app(SOURCE_PATHS_FIXTURE);
    let mut harness = app_ui_harness(app);
    event_stream::serve(socket, harness.ctx.clone());
    harness.run_steps(3);
    assert_eq!(
        harness.state().history.next_seq(),
        0,
        "guard: nothing may have been recorded before the burst fires"
    );

    let payloads: Vec<String> = (0..CLIENTS).map(burst_payload).collect();
    let mut children = spawn_concurrent_clients(&config_home, CLIENTS);
    assert_all_alive(&mut children);

    let before = harness.state().history.next_seq();
    write_all_stdins(&mut children, &payloads);

    // Phase 1: step frames as fast as possible while the children are still
    // running, so the frames that absorb the burst are the ones being timed.
    let mut reaped = vec![false; CLIENTS];
    let mut durations: Vec<Duration> = Vec::new();
    let deadline = Instant::now() + ARRIVAL_DEADLINE;
    loop {
        let start = Instant::now();
        harness.run_steps(1);
        durations.push(start.elapsed());
        if poll_exits(&mut children, &mut reaped) {
            break;
        }
        assert!(
            Instant::now() < deadline,
            "the concurrent clients never all exited; reaped={reaped:?}"
        );
    }
    let burst_frames = durations.len();

    // Phase 2: keep stepping (and timing) until the timeline stops growing.
    durations.extend(step_until_settled(&mut harness));

    let after = harness.state().history.next_seq();
    let delta = after - before;

    let max = durations.iter().max().copied().unwrap_or_default();
    let total: Duration = durations.iter().sum();
    let mean = total / durations.len() as u32;
    let mut sorted = durations.clone();
    sorted.sort();
    let median = sorted[sorted.len() / 2];

    let received = event_stream::received_count();
    let discarded = event_stream::discarded_count();
    let dropped = event_stream::dropped_count();
    let seen_by_loop = received + discarded + dropped;
    let kernel_lost = BURST_TOTAL as u64 - seen_by_loop;

    eprintln!(
        "[10-02 Task 3] frame cadence through a {CLIENTS}-client concurrent burst\n  \
         frames: {} timed ({burst_frames} while the clients were still running)\n  \
         recorded during the window: {delta}/{BURST_TOTAL}\n  \
         step durations: max={max:?} median={median:?} mean={mean:?} (ceiling \
         {FRAME_STALL_CEILING:?})\n  \
         counters: received={received} discarded={discarded} dropped={dropped}\n  \
         accounting: {seen_by_loop} reached the receive loop, {kernel_lost} lost in the kernel \
         before it (recvspace 4096), channel capacity {}",
        durations.len(),
        event_stream::CHANNEL_CAPACITY,
    );

    // ---- 1. The idle-app guard ----
    assert!(
        delta > 0,
        "the recorded event count must have grown during the timed window -- a delta of {delta} \
         would mean this test measured an idle application rather than a burst"
    );

    // ---- 2. Frame cadence ----
    assert!(
        max < FRAME_STALL_CEILING,
        "the slowest single frame took {max:?}, at or over the {FRAME_STALL_CEILING:?} stall \
         ceiling (median {median:?}, mean {mean:?} across {} frames)",
        durations.len()
    );

    // ---- 3. Loss was counted, not stalled ----
    assert_eq!(
        discarded, 0,
        "a discard is a wire-shape rejection, not load -- four concurrent real clients producing \
         one would be a genuine finding about the datagram path"
    );
    assert!(
        seen_by_loop <= BURST_TOTAL as u64,
        "the receive loop cannot have seen more than the {BURST_TOTAL} datagrams that were sent, \
         got {seen_by_loop}"
    );
    assert_eq!(
        delta, received,
        "everything the channel delivered must have reached the TIMELINE: {received} were \
         delivered but {delta} were recorded. A gap here means events were drained and thrown away"
    );

    // ---- 4. The app is not wedged ----
    let probe_symbol = "still_live_after_the_burst";
    let probe_id = format!("{HOOK_REPO_RELATIVE}::{probe_symbol}");
    run_client(
        &config_home,
        &write_payload(
            HOOK_FILE_PATH,
            &format!("pub fn {probe_symbol}() -> usize {{ 0 }}\n"),
        ),
    );
    let probe_deadline = Instant::now() + ARRIVAL_DEADLINE;
    while !recorded_node_ids(harness.state()).contains(&probe_id) {
        assert!(
            Instant::now() < probe_deadline,
            "the post-burst liveness probe `{probe_id}` never reached the timeline -- the app \
             absorbed the burst but is wedged afterwards"
        );
        std::thread::sleep(Duration::from_millis(10));
        harness.run_steps(1);
    }
    let app = harness.state();
    assert!(
        app.model
            .as_ref()
            .is_some_and(|model| model.index.contains_key(&probe_id)),
        "the liveness probe must have been APPLIED as well as recorded -- `{probe_id}` is missing \
         from the live model"
    );
    assert_eq!(
        app.history.next_seq(),
        after + 1,
        "the liveness probe must have recorded exactly one further event"
    );

    let _ = std::fs::remove_dir_all(&config_home);
}
