//! ROADMAP SC-2 and SC-4, proven by ONE harness rather than two (plan 10-02).
//!
//! A ~100-event burst (D-01's locked scale) generated by FOUR concurrent real
//! `seam-client` subprocesses, landing in one receive loop and one timeline.
//! That combination proves the 200ms hook budget AND the arrival-ordering
//! guarantee in one place, and builds the expensive subprocess infrastructure
//! once.
//!
//! **Why this infrastructure is genuinely new.** Two existing things look like
//! they already do it and do not:
//!
//! - `tests/event_stream.rs::concurrent_senders_each_deliver_every_message_whole`
//!   (06-03) drives raw `UnixDatagram::unbound()` senders from THREADS inside
//!   one process. No real client binary is involved anywhere in it.
//! - `common::run_client` (07-04, via 10-01) is the only real-binary helper,
//!   and it blocks on `wait_with_output()` before returning. A loop over it is
//!   SEQUENTIAL by construction, and would pass against a server with no
//!   concurrency handling whatsoever.
//!
//! **What makes "concurrent" a fact here rather than a timing heuristic.**
//! `seam-client`'s `main` reads stdin to EOF (`read_to_string`) before it does
//! any work at all, so a child spawned with a PIPED BUT UNWRITTEN stdin is
//! blocked and alive. [`spawn_concurrent_clients`] returns every `Child` handle
//! having written nothing and waited on nothing; [`assert_all_alive`] then calls
//! `try_wait()` on each and requires `None` from all of them, which is a proof
//! that all four processes exist at the same instant. Only then does
//! [`write_all_stdins`] release them, all within microseconds of each other.
//!
//! **Delivery is MEASURED, never assumed.** `net.local.dgram.recvspace` is 4096
//! on this machine (measured three times across 06-01/06-02/06-03), so an
//! unpaced burst genuinely drops datagrams in the kernel -- 06-03 measured
//! 59.2%/60.2%/64.0% delivered across three runs of an unpaced 4x100 burst.
//! Every test below asserts the properties that survive load (no corruption, no
//! duplication, per-client order preserved, a floor on the total) and PRINTS the
//! real ratio. A test demanding 100/100 here is a test that flakes, and lowering
//! a flaky assertion later is how a phase quietly stops proving anything.
//!
//! Additive by construction: `tests/event_stream.rs` is Phase 6's regression net
//! and is not touched, and no production source changes in this plan.

// TEMPORARY, for this one commit only: plan 10-02 Task 1 delivers the
// concurrency harness (`spawn_concurrent_clients`/`assert_all_alive`/
// `write_all_stdins`/`wait_all_clients`/`poll_exits`) while Tasks 2 and 3 are
// its first callers, and `cargo clippy --all-targets -- -D warnings` is a phase
// gate. This attribute is REMOVED in Task 3, at which point every item in this
// file is genuinely reached -- it is not the blanket allow `common/mod.rs`
// legitimately carries.
#![allow(dead_code)]

mod common;

use std::io::{Read, Write};
use std::os::unix::ffi::OsStrExt;
use std::path::Path;
use std::process::{Child, Command, ExitStatus, Stdio};
use std::sync::Mutex;
use std::time::Duration;

use seam_core::GraphEvent;
use seam_explorer_egui::event_stream;

use common::{
    client_binary, run_client, temp_config_home, wait_until, write_payload, HOOK_FILE_PATH,
    HOOK_REPO_RELATIVE,
};

// ---------------------------------------------------------------------
// Locked scale and budgets
// ---------------------------------------------------------------------

/// Four, mirroring 06-03's proven four-sender shape -- but four real OS
/// processes rather than four threads.
const CLIENTS: usize = 4;

/// 25 each, so the burst totals D-01's ~100 events.
const SYMBOLS_PER_CLIENT: usize = 25;

/// D-01's locked burst scale. Declared separately and cross-checked against
/// the two constants above, so a later edit to either cannot silently change
/// what this file claims to measure.
const BURST_TOTAL: usize = 100;

/// Serializes every test in this file. Tasks 2 and 3 drive the process-global
/// receiver (`event_stream::serve` plus the `received_count`/`discarded_count`/
/// `dropped_count` it backs), so one lock for the whole file, following
/// `timeline_reconstruction.rs`'s and `crash_relaunch.rs`'s one-lock-per-file
/// discipline.
///
/// This is a plain PROCESS-LOCAL mutex, not a file lock: it serializes tests
/// inside THIS binary and nothing else. Cross-process safety comes entirely
/// from `common::temp_config_home` embedding `std::process::id()`.
static SERVE_TEST_LOCK: Mutex<()> = Mutex::new(());

/// Generous: this waits on real process spawns plus real socket hops, and only
/// ever runs to completion when something has genuinely gone wrong.
const ARRIVAL_DEADLINE: Duration = Duration::from_secs(10);

// ---------------------------------------------------------------------
// The payload
// ---------------------------------------------------------------------

/// The tag that carries a client's identity into every id it advertises.
fn client_tag(index: usize) -> String {
    format!("c{index}")
}

/// One symbol name, zero-padded so lexicographic order and numeric order
/// coincide -- which is what lets [`reference_order`] state the expected
/// emission order without restating `detect`'s `BTreeSet` semantics.
fn symbol(client: usize, n: usize) -> String {
    format!("{}_sym_{n:02}", client_tag(client))
}

/// The node id `seam-client` will advertise for `symbol(client, n)`, built from
/// DP-07-01's `{source_file}::{symbol}` identity and
/// [`common::HOOK_REPO_RELATIVE`] -- never by reading an id back out of the app
/// and re-parsing it. An expectation read out of the system under test cannot
/// fail (`timeline_reconstruction.rs`'s discipline).
fn expected_node_id(client: usize, n: usize) -> String {
    format!("{HOOK_REPO_RELATIVE}::{}", symbol(client, n))
}

/// The order one client's advertisements are emitted in, which Task 1 PROVES
/// against a real single-client run rather than asserting from the source of
/// `detect`.
fn reference_order(client: usize) -> Vec<String> {
    let mut ids: Vec<String> = (0..SYMBOLS_PER_CLIENT)
        .map(|n| expected_node_id(client, n))
        .collect();
    // Sorted explicitly rather than relying on the zero-padding to make the
    // generated order already lexicographic: the claim being expressed is
    // "lexicographic", so the code should say it.
    ids.sort();
    ids
}

/// A `Write`-shaped hook payload declaring `SYMBOLS_PER_CLIENT` top-level
/// `pub fn`s named `symbol(client, 0..SYMBOLS_PER_CLIENT)`.
///
/// Three constraints on the generated content, each load-bearing:
///
/// - **No `::` anywhere, and no top-level `use` line.** Both of `detect`'s
///   reference rules key on those (`collect_import` wants a column-zero
///   `use `; `collect_qualified_calls` walks back from every `(` and keeps the
///   run only if it contains `::`). Any reference would add `AddEdge` events,
///   making the emitted count per client something other than
///   `SYMBOLS_PER_CLIENT` and turning every count assertion in this file into
///   guesswork. The bodies are therefore `{ 0 }` with no calls. Task 1 CHECKS
///   this behaviourally rather than trusting it.
/// - **The client index is in the symbol name**, so the resulting node id
///   (`src/auth/login.rs::c2_sym_07`) carries its own origin. Attribution in
///   the merged timeline is then a property of the data and needs no side
///   channel.
/// - **The edited file is a real `source_file` of the fixture**
///   ([`common::HOOK_FILE_PATH`] is the `source_file` of fixture node `a1`), so
///   sibling inheritance resolves every advertised node to a concrete
///   community and every event is genuinely APPLIED and therefore RECORDED. An
///   unknown file would leave the events parked in the unknown bucket or minted
///   into a `__live__:` community, and an ordering assertion over events that
///   never reached the history would be measuring nothing.
///
/// `tool_response.originalFile` is `null` in `common::write_payload`'s captured
/// shape, so this reads as a CREATE: the before-text is empty and all
/// `SYMBOLS_PER_CLIENT` definitions are additions.
fn burst_payload(client: usize) -> String {
    let mut content = String::new();
    for n in 0..SYMBOLS_PER_CLIENT {
        // `-> usize { 0 }` rather than a bare `{}` so the lines look like real
        // code, while still containing no parenthesised call and no path
        // separator for `collect_qualified_calls` to find.
        content.push_str(&format!(
            "pub fn {}() -> usize {{ 0 }}\n",
            symbol(client, n)
        ));
    }
    write_payload(HOOK_FILE_PATH, &content)
}

// ---------------------------------------------------------------------
// The concurrency harness -- split where `common::run_client` is not
// ---------------------------------------------------------------------

/// Spawns `count` real `seam-client` processes with piped stdin and writes
/// NOTHING to any of them, returning every handle.
///
/// **This function waits on nothing, and that is the whole point.** It is the
/// mitigation for T-10-02-02 and for research's Pitfall 3: `common::run_client`
/// blocks on `wait_with_output()` before returning, so a loop over it LOOKS
/// like a multi-client test while being sequential by construction -- and would
/// pass against a server with no concurrency handling at all. Splitting spawn
/// from wait is what makes four-at-once achievable; [`assert_all_alive`] is
/// what makes it a checked fact.
///
/// Each child gets `XDG_CONFIG_HOME` set and `CLAUDE_PROJECT_DIR` removed, so
/// it independently resolves the same socket path through
/// `seam_core::default_socket_path` -- exactly as `common::run_client` does.
fn spawn_concurrent_clients(config_home: &Path, count: usize) -> Vec<Child> {
    let binary = client_binary();
    (0..count)
        .map(|index| {
            Command::new(&binary)
                .env("XDG_CONFIG_HOME", config_home)
                .env_remove("CLAUDE_PROJECT_DIR")
                .stdin(Stdio::piped())
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()
                .unwrap_or_else(|e| {
                    panic!(
                        "spawn concurrent client {index} at {}: {e}",
                        binary.display()
                    )
                })
        })
        .collect()
}

/// Requires every child to still be running, at one instant.
///
/// This is the deterministic core of this file's concurrency claim. `main` in
/// `seam-client` calls `read_to_string` on stdin before it does anything else,
/// so a child whose stdin is piped and UNWRITTEN is parked in its own `read`.
/// `try_wait()` returning `None` for all of them therefore means all `count`
/// processes genuinely exist simultaneously -- no sleep, no "spawned close
/// together and hope", nothing timing-dependent.
fn assert_all_alive(children: &mut [Child]) {
    let total = children.len();
    for (index, child) in children.iter_mut().enumerate() {
        let status = child
            .try_wait()
            .unwrap_or_else(|e| panic!("try_wait on concurrent client {index}: {e}"));
        assert!(
            status.is_none(),
            "concurrent client {index} had already exited with {status:?} before any stdin was \
             written -- every one of the {total} children must be blocked in its own stdin read at \
             this instant, which is what makes 'all {total} ran at once' a fact rather than a \
             timing heuristic"
        );
    }
}

/// Releases every child within microseconds of the others by writing its
/// payload and CLOSING its stdin (the `drop` is what produces the EOF
/// `read_to_string` is waiting for).
fn write_all_stdins(children: &mut [Child], payloads: &[String]) {
    assert_eq!(
        children.len(),
        payloads.len(),
        "one payload per child, or a client would be released with nothing to do"
    );
    for (index, (child, payload)) in children.iter_mut().zip(payloads).enumerate() {
        let mut stdin = child
            .stdin
            .take()
            .unwrap_or_else(|| panic!("child {index}'s stdin was piped"));
        // The write result is deliberately ignored, matching `common::run_client`
        // and `fail_open.rs`: a client that declines an over-ceiling payload
        // closes the pipe, and the writer seeing that is correct behaviour
        // rather than a test failure.
        let _ = stdin.write_all(payload.as_bytes());
        drop(stdin);
    }
}

/// Waits on every child AFTER all of them have been released, asserting the
/// hook contract on each: exit 0, empty stdout, empty stderr.
fn wait_all_clients(children: Vec<Child>) {
    let mut children = children;
    for (index, child) in children.iter_mut().enumerate() {
        let status = child
            .wait()
            .unwrap_or_else(|e| panic!("wait for concurrent client {index}: {e}"));
        assert_hook_contract(index, child, status);
    }
}

/// The hook contract, in one place so the blocking path ([`wait_all_clients`])
/// and the frame-stepping path ([`poll_exits`]) cannot drift about what a
/// well-behaved invocation looks like.
///
/// stdout/stderr are read from the piped handles rather than through
/// `wait_with_output`, because the cadence test must reap its children with
/// `try_wait` while it keeps stepping frames and so cannot consume them.
fn assert_hook_contract(index: usize, child: &mut Child, status: ExitStatus) {
    assert!(
        status.success(),
        "concurrent client {index} must exit 0 like any hook, got {status:?}"
    );
    let mut stdout = String::new();
    if let Some(mut handle) = child.stdout.take() {
        let _ = handle.read_to_string(&mut stdout);
    }
    let mut stderr = String::new();
    if let Some(mut handle) = child.stderr.take() {
        let _ = handle.read_to_string(&mut stderr);
    }
    assert_eq!(stdout, "", "concurrent client {index} must print nothing");
    assert_eq!(
        stderr, "",
        "concurrent client {index} must print nothing to stderr"
    );
}

/// Polls every not-yet-reaped child ONCE, recording any that have exited and
/// asserting the hook contract on it there and then. Returns `true` once every
/// child has been accounted for.
///
/// Non-blocking on purpose: the cadence test has to keep driving real frames
/// while the burst lands, so it cannot afford a blocking `wait`.
fn poll_exits(children: &mut [Child], reaped: &mut [bool]) -> bool {
    for (index, child) in children.iter_mut().enumerate() {
        if reaped[index] {
            continue;
        }
        let status = child
            .try_wait()
            .unwrap_or_else(|e| panic!("try_wait on concurrent client {index}: {e}"));
        if let Some(status) = status {
            assert_hook_contract(index, child, status);
            reaped[index] = true;
        }
    }
    reaped.iter().all(|done| *done)
}

// ---------------------------------------------------------------------
// Small shared readers
// ---------------------------------------------------------------------

fn assert_sun_path_fits(path: &Path) {
    let len = path.as_os_str().as_bytes().len();
    assert!(
        len <= seam_core::MAX_SUN_PATH_BYTES,
        "socket path is {len} bytes, over the {} byte sun_path ceiling: {}",
        seam_core::MAX_SUN_PATH_BYTES,
        path.display()
    );
}

/// The id an `AddNode` carries, or nothing for any other event kind.
fn node_id_of(event: &GraphEvent) -> Option<String> {
    match event {
        GraphEvent::AddNode { id, .. } => Some(id.clone()),
        _ => None,
    }
}

// ---------------------------------------------------------------------
// Task 1 -- the reference run
// ---------------------------------------------------------------------

/// ONE client, through `common::run_client`, fixing the per-client emission
/// order every later assertion is measured against.
///
/// Three things this test establishes, in order:
///
/// 1. **The payload produces NODES ONLY.** Exactly `SYMBOLS_PER_CLIENT`
///    `AddNode` events arrive and ZERO `AddEdge` events, which is
///    [`burst_payload`]'s no-`::`/no-`use` constraint CHECKED rather than
///    assumed. Any edge would make the per-client count something other than
///    `SYMBOLS_PER_CLIENT` and turn every count assertion in this file into
///    guesswork.
/// 2. **The emitted order is the lexicographic order of the symbol names**,
///    which is what `detect`'s `BTreeSet` set-difference determinism means in
///    practice. [`reference_order`] is then the authority every later
///    assertion compares against, so no test in this file assumes `detect`'s
///    internal iteration order.
/// 3. **It WARMS the client binary** for the budget measurement in
///    `a_concurrent_burst_stays_inside_the_hook_budget`. WINDOWS 34: the first
///    execution of a freshly built binary costs 270-319ms (host-OS per-inode
///    overhead, not client code) versus ~5ms warm. Cargo gives no ordering
///    guarantee between tests, so that test warms explicitly as well -- this
///    is a useful side effect, not a dependency.
///
/// A single client's 25 small datagrams through a warm receive loop should
/// arrive whole, so the count below is an EXACT assertion, not a floor. If it
/// ever fails, that is a finding about the kernel receive buffer at this
/// datagram size that Task 2's numbers depend on -- report it with the real
/// counters rather than lowering the bar.
#[test]
fn a_single_client_reference_run_fixes_the_per_client_emission_order() {
    let _guard = SERVE_TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());

    let config_home = temp_config_home("c1ref");
    let socket_path = seam_core::socket_path_from(config_home.to_str(), None)
        .expect("the socket path must resolve from an explicit base");
    assert_sun_path_fits(&socket_path);

    let socket =
        event_stream::bind_at(&socket_path).expect("bind_at must succeed for a fresh path");
    // `spawn_receiver`, not `serve`: this test wants the RAW arrival list
    // including any event kind, so it can assert that no `AddEdge` was emitted
    // at all. An edge that was parked or dropped by the apply pipeline would
    // never reach a history, so a history-level check could not see it.
    let receiver = event_stream::spawn_receiver(socket, egui::Context::default());

    run_client(&config_home, &burst_payload(0));

    let mut drained: Vec<GraphEvent> = Vec::new();
    wait_until(ARRIVAL_DEADLINE, || {
        drained.extend(receiver.drain());
        drained.len() >= SYMBOLS_PER_CLIENT
    });
    // One more poll after the wait: a datagram that arrived during the final
    // sleep would otherwise be invisible to the exactness assertions below.
    drained.extend(receiver.drain());

    let edges = drained
        .iter()
        .filter(|event| !matches!(event, GraphEvent::AddNode { .. }))
        .count();
    assert_eq!(
        edges, 0,
        "the generated content must produce NODES ONLY -- {edges} non-AddNode events arrived, so \
         `burst_payload`'s no-`::`/no-`use` constraint has been broken and every per-client count \
         in this file is now guesswork. Arrivals: {drained:?}"
    );
    assert_eq!(
        drained.len(),
        SYMBOLS_PER_CLIENT,
        "exactly {SYMBOLS_PER_CLIENT} AddNode events must arrive from one client; received={} \
         discarded={} dropped={}. Do NOT lower this -- a loss here is a finding about the kernel \
         receive buffer at this datagram size, and Task 2's numbers depend on it",
        receiver.stats().received(),
        receiver.stats().discarded(),
        receiver.stats().dropped()
    );

    let arrived: Vec<String> = drained.iter().filter_map(node_id_of).collect();
    let expected = reference_order(0);
    eprintln!(
        "[10-02 Task 1] reference emission order for client 0 ({} ids): {:?}",
        arrived.len(),
        arrived
    );
    assert_eq!(
        arrived, expected,
        "one client's emission order must be the lexicographic order of its symbol names -- that \
         is what `detect`'s BTreeSet set-difference determinism means in practice, and it is what \
         every per-client subsequence assertion in this file is measured against"
    );

    let _ = std::fs::remove_dir_all(&config_home);
}
